http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: ['/api/users','/api/user/*']
  order:
    host: localhost
    paths: ['/api/orders','/api/orders/*']
  product:
    host: localhost
    paths: ['/api/products','/api/products/*']
  payment:
    host: localhost
    paths: ['/api/payments','/api/payments/*']
  cart:
    host: localhost
    paths: ['/api/carts','/api/carts/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: 'http://localhost:5000'
  orderService:
    url: 'http://localhost:6000'
  productService:
    url: 'http://localhost:4000'
  paymentService:
    url: 'http://localhost:3000'
  cartService:
    url: 'http://localhost:3500'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
  productPipeline:
    apiEndpoints:
      - product
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
  paymentPipeline:
    apiEndpoints:
      - payment
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: paymentService
              changeOrigin: true
  cartPipeline:
    apiEndpoints:
      - cart
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cartService
              changeOrigin: true